name: Run pre-merge Databricks tests

on:
  pull_request:

env:
  # Replace this value with your workspace instance name.
  DATABRICKS_HOST: https://adb-5741265693868923.3.azuredatabricks.net

jobs:
  unit-test-notebook:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      -name: linting
       uses: Silleellie/pylint-github-action@v2
       with:
         lint-path: notebooks
         python-version: 3.9
         readme-path: README.md
         # Text to display in the badge
         #
         # Optional, Default: PyLint
         badge-text: PyLint
         # Color of the badge for pylint scores < 5.
         # Hex, rgb, rgba, hsl, hsla and css named colors can all be used
         #
         # Optional, Default: red
         color-bad-score: red
    
         # Color of the badge for pylint scores in range [5,8).
         # Hex, rgb, rgba, hsl, hsla and css named colors can all be used
         # 
         # Optional, Default: orange
         color-ok-score: orange
    
        # Color of the badge for pylint scores in range [8,10).
        # Hex, rgb, rgba, hsl, hsla and css named colors can all be used
        #
        # Optional, Default: yellow
        color-good-score: yellow
    
        # Color of the badge for pylint scores == 10.
        # Hex, rgb, rgba, hsl, hsla and css named colors can all be used
        #
        # Optional, Default: brightgreen
        color-perfect-score: brightgreen
        
      - name: Checkout repo
        uses: actions/checkout@v4 
      - name: Run test notebook
        uses: databricks/run-notebook@main
        with:
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}

          local-notebook-path: notebooks/run_unit_tests.py

          existing-cluster-id: 0326-091429-s9i8f8ii

          git-commit: "${{ github.event.pull_request.head.sha }}"

          # Grant all users view permission on the notebook's results, so that they can
          # see the result of the notebook, if they have related access permissions.
          access-control-list-json: >
            [
              {
                "group_name": "users",
                "permission_level": "CAN_VIEW"
              }
            ]
          run-name: "EDA transforms helper module unit tests"
        
